version: '3'
services:
  app:
    build: .
    command: ["yarn","start"]
    #command: /bin/bash -c "while true; do sleep 10; done"
    volumes:
      - .:/usr/src/app
    ports:
      - "127.0.0.1:5000:5000"
